# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\encwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 136, 531, 24))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.fileNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.fileNameInput.setGeometry(QtCore.QRect(10, 20, 531, 24))
        self.fileNameInput.setText("")
        self.fileNameInput.setReadOnly(True)
        self.fileNameInput.setObjectName("fileNameInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -2, 56, 24))
        self.label.setObjectName("label")
        self.opModeInput = QtWidgets.QComboBox(self.centralwidget)
        self.opModeInput.setGeometry(QtCore.QRect(11, 110, 53, 20))
        self.opModeInput.setObjectName("opModeInput")
        self.opModeInput.addItem("")
        self.opModeInput.addItem("")
        self.opModeInput.addItem("")
        self.opModeInput.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 86, 101, 24))
        self.label_2.setObjectName("label_2")
        self.keyInput = QtWidgets.QLineEdit(self.centralwidget)
        self.keyInput.setGeometry(QtCore.QRect(10, 65, 531, 22))
        self.keyInput.setObjectName("keyInput")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 42, 56, 24))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 552, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionEncrypt = QtWidgets.QAction(MainWindow)
        self.actionEncrypt.setEnabled(False)
        self.actionEncrypt.setObjectName("actionEncrypt")
        self.actionDecrypt = QtWidgets.QAction(MainWindow)
        self.actionDecrypt.setEnabled(False)
        self.actionDecrypt.setObjectName("actionDecrypt")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionEncrypt)
        self.menu.addAction(self.actionDecrypt)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SAFER Encrypt/Decrypt tool"))
        self.progressBar.setFormat(_translate("MainWindow", "%v of %m bytes"))
        self.label.setText(_translate("MainWindow", "File name"))
        self.opModeInput.setItemText(0, _translate("MainWindow", "ECB"))
        self.opModeInput.setItemText(1, _translate("MainWindow", "CBC"))
        self.opModeInput.setItemText(2, _translate("MainWindow", "CFB"))
        self.opModeInput.setItemText(3, _translate("MainWindow", "OFB"))
        self.label_2.setText(_translate("MainWindow", "Operation mode"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.actionDecrypt.setText(_translate("MainWindow", "Decrypt"))
